### ISSUE TITLE
redirect ps4 and xbox to r6db

### ISSUE THREAD

**Issue by LaxisB** [r6db/r6db#1]
we should redirect ps4 and xbox to the root page now that we're uni-platform.
there's no reason to keep the 'old' sites if we can just redirect/rewrite.

ping: @NaughtyMuppet

**Comment by LaxisB** [comment]
@NaughtyMuppet are we ready to do this, or do you need some preptime on the ops side?

**Comment by NaughtyMuppet** [comment]
Should be quite easy as an nginx rule, but my backlog is filled for today. I don't see this as urgent

**Comment by LaxisB** [comment]
whoops, wrong button.
just close once you get to it

**Comment by RaGMagicTrick** [comment]
Hey men can you help me??

**Comment by LaxisB** [comment]
@RaGMagicTrick yeah, just open a new issue with your problem

**Comment by NaughtyMuppet** [comment]
Finished last night
