### ISSUE TITLE
Some stats (timePlayed) not updated in .json header

### ISSUE THREAD

**Issue by monolied** [r6db/r6db#100]
This is about timePlayed for game modes casual and ranked. Up until ~06.02., I'd find the latest data in the stats header/top level of the json export. When I now look into the .json, I find the acumulated values for timePlayed in the last field of the "progressions"-array, but these values aren't in the header stats. Instead, there are values of on or before 06.02.
The other values (deaths, kills, lost, won, played) look ok. timePlayed for operators also seems unaffected.

hth, m.

**Comment by NaughtyMuppet** [comment]
If I understand this correctly it will be fixed starting tomorrow
