### ISSUE TITLE
bug with r6db

### ISSUE THREAD

**Issue by KliDD** [r6db/r6db#106]
hi last season I was ban of R6DB I totally accept but you told me that I would be unban at the beginning of the next season as it was my first ban and I see that I still have not been unban thank you for helping me

My R6DB is : https://r6db.com/player/e8fb0849-2dd5-4b44-bdc1-e1d7a0f6365b
Uplay : xCrEaTiOn_FiZ_

**Comment by NaughtyMuppet** [comment]
Not a bug, if you're banned for boosting it doesn't help when you're copper 4 in one region and diamond in the other. Extended to perm.

**Comment by KliDD** [comment]
sorry but you know road to cooper ? now im gonna to up dia --"
seriously you ban me for anithing
