### ISSUE TITLE
better nav

### ISSUE THREAD

**Issue by LaxisB** [r6db/r6db#109]
the current topbar navigation will get too crowded with the planned features.
instead, we should switch back to the sidebar menu approach that we had before.  
  
improvements to topbar: 
 - more space for links
 - can include secondary links (discord, social media, etc)

improvements to old sidebar/design: 
 - due to the fixed-width content we can still use media queries. no layout changes after the max-width.

tasks:
 - [ ] integration into redux
 - [ ] auto-close on menu change
 - [ ] swipe to open? (has to include fall-open and fall-close)
 - [ ] topbar
   - mobile: fixed bar; burger and full-width searchbar (with background?)
   - tablet: fixed bar; burger and right floating searchbar (max-width ~200px?)
   - desktop: only floating searchbar.

 - [ ] define content alignment
   - left aligned next to the menu
   - centered on the screen (aka menu overlayed)
   - centered on the content area (non-menu space)

**Comment by LaxisB** [comment]
should we do the 'swipe to open' ? that gets quite involved with animations

**Comment by LaxisB** [comment]
basic impl pushed here: https://github.com/r6db/frontend/commit/fe635379889ff442f29168f625627761bb1f7be5

**Comment by marcopixel** [comment]
restructured the menu with https://github.com/r6db/frontend/commit/fcc8dcc46815b0f782835822ba2bba6d09f0491b
