### ISSUE TITLE
Add: Hide inactive MMR Region (Europe, America, Asia)

### ISSUE THREAD

**Issue by GoldMath** [r6db/r6db#112]
Hi,

Sometimes it can be difficult to read a MMR graph when you around 2500.

Can you add a way to hide/toggle other Region by clicking on their names under the graph?
To go further: maybe a way to auto-hide inactive region?  

_Exemple here: I want to hide America and Asia._
![mmr](https://user-images.githubusercontent.com/7282547/39174886-28d7f462-47a9-11e8-8312-7d7c8e703fb1.JPG)

**Comment by GoldMath** [comment]
Hey, I just checked the _dev_, it's work wonderfully! Great job!

**Comment by LaxisB** [comment]
nice!  
i'll deploy it with the next batch of changes and close the ticket when its live
