### ISSUE TITLE
Get rank not working

### ISSUE THREAD

**Issue by brunohenriquesk1** [r6db/r6db#113]
not sure what's wrong but I'm getting the following json from the request
`"serverUtcTime": "2018-05-19 10:00:42",
"resource": "/public/r6karma/v1/players",
"httpCode": 400,
"errorCode": "Core::1",
"message": "",
"moreInfo": ""`
 
My url get request is "https://public-ubiservices.ubi.com/v1/spaces/05bfb3f7-6c21-4c42-be1f-97a33fb5cf66/sandboxes/OSBOR_PS4_LNCH_A/r6karma/players?board_id=pvp_ranked&profile_ids="+ profileId

any ideia? Thanks

**Comment by LaxisB** [comment]
you need to pass a region to check (`&region_id=@region`). i fixed the docs for getRank consolel here.  
  
this is however not a r6db ticket. it's ubisofts api.
