### ISSUE TITLE
Make JSON data programmatically accessible

### ISSUE THREAD

**Issue by element-code** [r6db/r6db#114]
Hi,

what do you guys think about making the data (possible the json files) accesibla via a simple interface.
*Im looking for pro's and con's*

**Comment by LaxisB** [comment]
we had an api, but had to shut it down due to gdpr compliance concerns.
it's not clear if we can provide this in the future or not

**Comment by element-code** [comment]
Hi,

i saw you republished the JSON Data..
Discussion again or ist this still covered by the GDPR?
