### ISSUE TITLE
Not all Operator-Icons on display

### ISSUE THREAD

**Issue by ghost** [r6db/r6db#115]
If I click on the Operator-Tab on a player and select no filter, not all Icons show up on the list.

![no_icon_1](https://user-images.githubusercontent.com/10185839/41970529-74815e46-7a0b-11e8-91cd-23071b28b333.JPG)
![no_icon_2](https://user-images.githubusercontent.com/10185839/41970530-74a0d802-7a0b-11e8-9417-b15a14622fcd.JPG)

**Comment by marcopixel** [comment]
We know about this issue and will fix it in the next few days. :+1:

**Comment by ghost** [comment]
Closing this since its not relevant anymore.
