### ISSUE TITLE
Add text endpoint

### ISSUE THREAD

**Issue by LaxisB** [r6db/r6db#18]
we had this at some point with the "imfeelinglucky" param.  
goal is to have an endpoint (at `/api/v2/text?name=<>&platform=<>` or something that returns a bit of text with the current level, rank wl and kd.  
also, it has to be an exception to the app-id rule so that the bots can actually call it

**Comment by LaxisB** [comment]
this was requested by https://twitter.com/Polare_

**Comment by NaughtyMuppet** [comment]
I finished community stats backend so I might just do it today, thinking it should have an ability to customize the fields returned with query params (and also, optionally a way to get it by ID)

**Comment by NaughtyMuppet** [comment]
https://github.com/r6db/r6db/wiki/feelinglucky
