### ISSUE TITLE
Manual rank/stat refresh button

### ISSUE THREAD

**Issue by NaughtyMuppet** [r6db/r6db#20]
We can set a key to redis with a TTL, then we can check it's TTL, if it still exists we don't allow update and we can display when you can update, otherwise update immediately and ?return the updated profile?

**Comment by LaxisB** [comment]
hmm,
i'd prefer a `updateAvailableAt` prop on a player with an exact Timestamp when an update is possible.  
then you'd either call it with `.../players/:id?forceUpdate=true` or the first request automatically updates the profile.
