### ISSUE TITLE
Player stats not refreshing

### ISSUE THREAD

**Issue by ghost** [r6db/r6db#26]
I keep trying to refresh my page and search my gamertag and my stats are not refreshing like I'm not gold 2 anymore or a level 127.

**Comment by NaughtyMuppet** [comment]
What's your username/platform?

**Comment by ghost** [comment]
So i just checked now and it has refreshed, so does it take time to refresh? Its not live?

**Comment by ghost** [comment]
The last time i checked was about 12 hours a go and so now 12 hours later it refreshed so that is take that long usually?

**Comment by NaughtyMuppet** [comment]
We refresh data once per day.
