### ISSUE TITLE
Shots fired / hits

### ISSUE THREAD

**Issue by monolied** [r6db/r6db#28]
I use the above markers to determine the development of my accuracy. They are part of the R6 stats server data (albeit only overall, not for casual/ranked respectively). This data is, alas, missing from your stats. Otherwise, it's nice, I like it.

**Comment by LaxisB** [comment]
yeah, we have accuracy in the stats, but not shots fired/hit seperate.  
what are you tracking exactly where accuracy isn't the viable?

**Comment by monolied** [comment]
I'm trying to find out if my accuracy improves (or gets worse), depending on decisions I make regarding fov, mouse settings, sights etc. I look at shots/hits, make setup changes, play, look again, subtract the first values and get a very nice accuracy  result for a short period. In the same time frame, the overall accuracy usually doesn't change at all. If I have an accuracy of 250/500 that is a remarkable value (it's an example!), but that just fades towards zero against the 200000 or whatever shots already fired.

**Comment by monolied** [comment]
... also, headshot count doesn't mean anything, if you can't relate it to shots fired. Also, I don't like that I have to go to r6tracker just for these two numbers.

... come to think of it, I *could* determine hits and shots fired via the hs / hits value within some +-50 shots... but still, would be nice to have that available with a higher precision and directly.

(btw I don't get the "hs ratio" value. With a value of ~40%, it's hard to imagine any meaningful relation that could represent...)

**Comment by monolied** [comment]
Just realised I find all that in the export... that's very nice! and sufficient for my usage.

**Comment by LaxisB** [comment]
for what it's worth, we also have an accuracy/headshot chart (the last one). You can compare up to 30 days there  
  
hs ratio is just headshots/kill ratio (e.g 40% of your kills are headshots)

i'll make a note about the additional stats. maybe i can show them in a tooltip when hovering accuracy or something.
