### ISSUE TITLE
current mmr doesnt correlate to global and region ranking

### ISSUE THREAD

**Issue by nutE-Vs** [r6db/r6db#32]
![whyyyyy](https://user-images.githubusercontent.com/32696674/31424348-adddf42a-ae27-11e7-866c-87856d690ef4.jpg)

i have a higher current and max mmr and he is still higher than me on the leader boards, i am just curios of how the leaderboard is determined. Thank you and i love the site

**Comment by LaxisB** [comment]
we don't use mmr directly in the leaderboard rankings.
our 'formula' is `skill - uncertainty`. there's a more in-depth explanation at the top of the [faq](https://r6db.com/faq)
