### ISSUE TITLE
Stats per seasons or adjustable time period on graps

### ISSUE THREAD

**Issue by kincsespeti** [r6db/r6db#33]
Hi,

wondering if it would be possible to extend the stat tracking to seasons.(like ranked k/d and so on)

Or adjusting the timelapse to show older daily stats (implying older daily stats are not discarded) either by shifting the observed period or by selecting a longer period.

**Comment by LaxisB** [comment]
@NaughtyMuppet that's up your alley. maybe a `timeframe=(season|30|<num>)` querystring?

**Comment by NaughtyMuppet** [comment]
Closed in favor of https://github.com/r6db/r6db/issues/33 with a narrower scope
