### ISSUE TITLE
Dubz mD on xbox boosted account using silvers currently #2 on leaderboards global (was #1)

### ISSUE THREAD

**Issue by asap777** [r6db/r6db#34]
So yea was wondering if the people who run r6db will look into this and tell me what they think...and maybe remove him from the leaderboards.

I havn't looked into other accounts yet but when Dubz mD on xbox was #1 (he is #2 now) on the leaderboards I checked his captures to see him play out of curiosity...to my surprise I expected much better gameplay for a 1st place diamond player...he plays like a gold...so I look up some players in his squad and they are silver rank. It looks like he is carrying a full silver squad for easy wins or "dubz" and easy kills for a nice 1.9kd.

**Comment by LaxisB** [comment]
can you grab some screenshots of this?
we can remove him once we have evidence of boosting.

**Comment by asap777** [comment]
High silver low golds also I have a video of his Xbox capture here that I
recorded using the apple screen capture

https://1drv.ms/v/s!Au_giIDCd4_7i0tDz6eS9Q4-8WtI

I think you play on PC but idk if you can tell he doesn’t play like a Xbox
diamond with a 1.9kd

I’m diamond on Xbox and I had a 1.4kd until I got into high plats/diamonds
and now I’m 1.3kd I’m 524 global 500 points into diamond 5123MMR and if you
want a clip of me playing just to compare I can send that too.

A 1.9kd vs diamond players is unrealistic especially how he plays. To me he
plays like a gold 2 and in the beginning of the clip he even gets stuck
trying to hold a bad angle in the bathroom.

**Comment by iNeedYouPSN** [comment]
That's true. 
1. He has a really Bad Movement and Aim
2. You can search his mates on r6db.com , so you can see that they are all Silvers and Gold IV players...
