### ISSUE TITLE
Custom Leaderboards

### ISSUE THREAD

**Issue by fhtyamamoto** [r6db/r6db#37]
As a normal player, I would like to create a Custom Leaderboard to add friends and known people by ID or Alias.

The Custom Leaderboard must allow up to 4 attributes to be selected, displayed, filtered and ordered:
- Rank (permanent)
- Level (permanent)
- Most Used Alias or Latest Alias (permanent)
- (Most Active) Region or Nationality (permanent)
- Ranked.WDR (default)
- Ranked.KDA (default)
- Most Picked Attack Char (Last 30 days)
- Most Picked Defensive Char (Last 30 days)
- Ranked.KDR (KDR != KDA)
- Knife Kills

As a Competitive Peer / eSports Stakeholder, I would like to create Custom Leaderboard to have an overview / snapshot of the teams per Region, per Season.

**Comment by NaughtyMuppet** [comment]
This is actually in my current plans, on 3rd place. First we'll finish up with the comparison's page, then community stats and then what I've been calling "lists", which is what You want.

**Comment by fhtyamamoto** [comment]
@NaughtyMuppet 
I couldn't find information on how to contribute to the project neither here on Github nor on GitLab.

**Comment by KristjanTammekivi** [comment]
@fhtyamamoto The backend projects are hidden right now. When the elixir version goes live we might open it up.

**Comment by NaughtyMuppet** [comment]
The backend projets are currently hidden. When the elixir version goes live we might open it up.

**Comment by LaxisB** [comment]
this should be resolved with the comparison now.
