### ISSUE TITLE
last_played is displayed incorrectly as today

### ISSUE THREAD

**Issue by NaughtyMuppet** [r6db/r6db#39]
https://r6db.com/player/1b50085a-8a20-4ce6-b75f-db6a00e4d718
Pretty sure Laxis didn't play yesterday

**Comment by LaxisB** [comment]
i don't know muppet.  
might be because i was logged in to uplay for wildlands
![laxis data](https://user-images.githubusercontent.com/8034086/32480603-e4cc74fc-c38f-11e7-84ea-e8ef7ea4a8ea.png)

**Comment by NaughtyMuppet** [comment]
Fixed with https://github.com/r6db/frontend/commit/908b988b8b56d10fc3b0764988300e651ceb7b8d
