### ISSUE TITLE
Missing profile

### ISSUE THREAD

**Issue by velekeyp** [r6db/r6db#40]
Hi this profile is missing from database, name: nutelladam  platform: psn

**Comment by LaxisB** [comment]
can you link your profile on ubi's page?  
it's unusual that we can't grab an accounts data
-> https://game-rainbow6.ubi.com

**Comment by velekeyp** [comment]
Problem solved :)

**Comment by LaxisB** [comment]
oh that was fast o.o i still can't find the profile on my end.
i'm assuming this is the profile: https://game-rainbow6.ubi.com/en-us/psn/player-statistics/1c0711f7-3e7d-4fd9-b139-7f1cce629493/multiplayer  
  
https://r6db.com/player/1c0711f7-3e7d-4fd9-b139-7f1cce629493 gives me a 404 on the profile data

**Comment by velekeyp** [comment]
https://r6db.com/player/b4368a9e-3a41-4d1d-91ae-29a731e2692c

**Comment by velekeyp** [comment]
"id":"b4368a9e-3a41-4d1d-91ae-29a731e2692c"
"userId":"1c0711f7-3e7d-4fd9-b139-7f1cce629493"

**Comment by LaxisB** [comment]
ah yeah; forgot that ubi uses userid in their urls.
thanks!
