### ISSUE TITLE
De-Reinforced using coppers to elo farm (PC - Global #1)

### ISSUE THREAD

**Issue by neo3224** [r6db/r6db#42]
Hes using few coppers to reach 8-9k ELO.
![tom clancy s rainbow six siege2017-11-2-20-24-0](https://user-images.githubusercontent.com/33540403/32647434-580d0cf2-c5f1-11e7-9b08-fd74a4e2193c.jpg)

**Comment by NaughtyMuppet** [comment]
Will be removed next cycle tomorrow afternoon
