### ISSUE TITLE
Remove Name history.

### ISSUE THREAD

**Issue by neo3224** [r6db/r6db#43]
Hi i wanna clear my allias history. I wanna start a new name with new sheet because i have a very confident history. Acc link: https://r6db.com/player/42198cd7-43f4-4688-9a37-98d66daf1bc3

**Comment by neo3224** [comment]
??

**Comment by LaxisB** [comment]
we don't remove aliases at all.  
the whole puropose of the site is to know who is who, so that would defeat its purpose.
  
hell, you could've hacked with an old name and then change your alias. we don't know.
