### ISSUE TITLE
api data object suggestion

### ISSUE THREAD

**Issue by darrencoen** [r6db/r6db#45]
`var json = api_returned_player_data_object;`

#1 Can the general stats be saved as snapshots to the progressions?
`json.stats.general` has 25 properties.
`json.progressions[i].stats.general` only has 3 properties. 

#2 Can operator data be changed to have null or 0 values instead of being undefined?
`json.stats.operator.sledge` I use sledge therefore i have data on him. he has a prop "kills" with value 100.
`json.stats.operator.echo` I don't have echo. There's no data for him. He has no property "kills" and thus undefined.
`json.stats.operator.sledge.kills + json.stats.operator.echo.kills` yields NaN when really it should result in 100.

this same issue is consistent in `json.progressions[i].stats.operator` values, and possibly elsewhere in the data.

![image](https://user-images.githubusercontent.com/611705/32744798-9765be8c-c865-11e7-9213-d08025fd3169.png)

I don't believe any of these suggestions would break your data, they'd just expand on it and make doing simple math/lookup a lot easier.
Thank you!

**Comment by NaughtyMuppet** [comment]
Implemented your second suggestion, will not do your first request though

**Comment by darrencoen** [comment]
@NaughtyMuppet out of curiosity, how come you are rejecting the first request? I figured you already have all of that data and are storing daily general stats.... whats a few more fields that you already have?
