### ISSUE TITLE
New Operators Icons (Vector .svg)

### ISSUE THREAD

**Issue by GoldMath** [r6db/r6db#46]
Hello,

Here are the incoming operators icons flatted in .SVG format.

Regards,

# White Noise
![newops](https://user-images.githubusercontent.com/7282547/33127221-dc53847e-cf87-11e7-81f5-10fa6871245c.png)

## **Zofia**
![zofia_badge](https://user-images.githubusercontent.com/7282547/32995633-9db94fd0-cd77-11e7-9b43-f6768eec4cd4.png) ![zofia flat](https://user-images.githubusercontent.com/7282547/32995813-3636f3a0-cd7a-11e7-9310-d57a1d647d69.jpg)

.SVG flat > [zofia_badge.zip](https://github.com/r6db/r6db/files/1486008/zofia_badge.zip)

## **Dokkaebi**
![dokkaeb-2i](https://user-images.githubusercontent.com/7282547/33020349-4b0f2eee-cdfe-11e7-836e-4714eb64735b.png) ![dokkaeb](https://user-images.githubusercontent.com/7282547/33020352-4e106b6c-cdfe-11e7-9604-a127d7eb52a6.jpg)

.SVG flat > [dokkaebi_badge.zip](https://github.com/r6db/r6db/files/1487756/dokkaebi_badge.zip)

## **Vigil**
![vigil](https://user-images.githubusercontent.com/7282547/33127009-fe26cc4c-cf86-11e7-879f-3a042df65b37.png) ![vigilflat](https://user-images.githubusercontent.com/7282547/33126967-c5814eb2-cf86-11e7-8781-354c6a97fa50.jpg)

.SVG flat > [vigil-badge.zip](https://github.com/r6db/r6db/files/1495896/vigil-badge.zip)

**Comment by NaughtyMuppet** [comment]
Brilliant, thanks!

**Comment by LaxisB** [comment]
Many thanks for those.
Added them in https://github.com/r6db/frontend/commit/348e1768a6a634bfbc95d82fb3eb55c37e3e384f

**Comment by GoldMath** [comment]
Hi,

We actually have SVG icons made by three different people.

The orignal maker (**DocYen**, from Reddit) of the previous icons (all other that Y2 S3&S4) updated his pack with the most recent. I recommend to merge them to unify the style.

https://www.reddit.com/r/Rainbow6/comments/7g4lwb/y2s4_operator_icons_download_in_comments/

Download link: https://drive.google.com/file/d/0BxYzSiVtQSX8Vlc0ckZRb2sxVE0/view
