### ISSUE TITLE
No exact search

### ISSUE THREAD

**Issue by velekeyp** [r6db/r6db#47]
My problem is that if I put the extract in the link true, it does not just give the same names, it does not spell the case, and even if there is no extra character, it does not even distinguish it. Here's an example, I called this name: SunsetRed. and who gives me the name I'm looking for, and even this is SunSetRed.Gun Can you really just list the exact same results?

**Comment by NaughtyMuppet** [comment]
Docs are a bit bad here, it exact should be 1 if you want exact search
for example /api/v2/players/?name=Muppet&platform=pc&exact=1 will return 0 results
