### ISSUE TITLE
Ranked data not updated following last session

### ISSUE THREAD

**Issue by DDavid972** [r6db/r6db#48]
First of all thanks a lot for R6DB. The website is very nice very useful.

I observed, today that there seems to be issues on recent data refresh. 

Following my last ranked session from yesterday, statistics have been updated on Ubi site but not on r6db. Total time on ranked  37h34 (R6DB) 38h30 (Ubi) 

Included, screenshot of the stats on R6DB and UBI.

![capture d ecran 2017-11-22 a 12 01 08](https://user-images.githubusercontent.com/32804141/33136993-186e6a24-cf7d-11e7-9d89-7c20ef7c4bdd.png)
![capture d ecran 2017-11-22 a 12 01 19](https://user-images.githubusercontent.com/32804141/33136994-1889efe2-cf7d-11e7-83d9-62b6fba4c82b.png)

**Comment by LaxisB** [comment]
how long ago has your session been exactly?
we update all players once a day

**Comment by DDavid972** [comment]
It was yesterday night and it finished at 1am (GMT-4).

I tought it was an hourly update.
I’ll check tomorrow to see if there is modification.

**Comment by dt-flo** [comment]
Is there a way to manually update the stats of a profile ?

**Comment by LaxisB** [comment]
not yet, but we planned that for the next api release
