### ISSUE TITLE
Global Rank Not Showing

### ISSUE THREAD

**Issue by thrtn** [r6db/r6db#51]
About 6-9 months ago, I opened a case asking about my global rank not showing up when I clicked on my profile. I was told that I was temporarily removed from the global leaderboard for being a suspected cheater, and that I would be put back onto the leaderboard as I remember. I still do not have a global rank and would like to see it, so please fix this issue that has been going on for close to a year now. (Uplay:  
thrtn. )

**Comment by NaughtyMuppet** [comment]
I'm pretty sure I didn't say anything about "temporarily" and "suspected"

**Comment by thrtn** [comment]
Actually I'm certain you said temporary. Maybe if you would just open your eyes for a sec and look back you most definitely said temporary you brain dead retard.

**Comment by thrtn** [comment]
And what did you even mean by confirmed cheater in the first place? Did someone like Remorce from PRO LEAGUE message you that I cheated? HES FAT AS FUCK

**Comment by thrtn** [comment]
Just a dogshit low gold player who complains about jager acog and ashes hitbox

**Comment by LaxisB** [comment]
jup, that's definitely the way to get yourself unbanned
