### ISSUE TITLE
Tracker is not updated!

### ISSUE THREAD

**Issue by TheeMarshmallow** [r6db/r6db#54]
The stats tracker isn't updated.

**Comment by LaxisB** [comment]
which profile and stat are you talking about?
it's hard to debug without any data

**Comment by yada-yoda** [comment]
My profile is not updated either -- I ranked up to plat 2 it did not update, nor did the mmr or uncertainty. r6.tracker.network did however update

**Comment by LaxisB** [comment]
tracker network updates on every request; we only update daily

**Comment by yada-yoda** [comment]
Any idea when you update daily? It's almost been 24 hours since I climbed, just curious. Any plans to go towards real time tracking?

**Comment by NaughtyMuppet** [comment]
Way too many players to track more often than once per day. Updates start around 1 in the morning CET and take several hours
