### ISSUE TITLE
New Operators 

### ISSUE THREAD

**Issue by CailiState** [r6db/r6db#60]
When will stats for the 3 new operators be put into the database?

**Comment by NaughtyMuppet** [comment]
Since the rainbow 6 website is broken for me so I need help from @LaxisB

**Comment by LaxisB** [comment]
also borked for me.
ubi seems to be in an infinite loop when loading some shizzle

**Comment by LaxisB** [comment]
@NaughtyMuppet it might be worth to check the results of `gamemodeoperatorpvp_matchwon`  
we already map to the known ops, so the last results with values should be the new ones.

i should have zofia>dok>vigil (playtime wise). so we can counter-check with that

**Comment by LaxisB** [comment]
ok, the site is working again:  
  
zofia: 3:C  
dok: 2:D  
vigil: 3:D
