### ISSUE TITLE
bulletsFired did not change between 12/12 and 12/18

### ISSUE THREAD

**Issue by monolied** [r6db/r6db#65]
Hello,

I pulled the json of my stats on Dec 12 and on Dec 18.
In both files I find 90871 as my bulletsFired value; bulletsHit and headshot increased in that timeframe, but bulletsFired didn't, which is, of course, theoretically not possible.

The value is also identical to the value presented by the Siege stats page. Since R6 can hardly know beforehand what my bulletsFired will be the next time I pull data, the only explanation atm would be that the Siege stats don't update bulletsFired correctly. Sure, that is their issue, but since you only present derived values, all your computations based on bulletsFired would be silently wrong...

Since R6 is only showing two digits for the accuracy, I can't tell you if your computations differ from theirs. But you might want to check if you can reproduce that issue - and you might be in a better position to file a bug report with R6 based on your findings. (I'd love to know anyway how you manage to pull your data from the R6 servers... checked the code but didn't find the relevant portion...)

PS: I just studied the json another bit, and it looks like it contains a history of stats, which also reflects the missing update of the bulletsFired value. In my case it must have lost track between 26.11. and 09.12.

hth, best regards, ml

**Comment by NaughtyMuppet** [comment]
Thanks for bringing this to our attention. Sadly it looks like this isn't something we can fix ourselves, as it's the value we get from Ubisoft. It appears to have started happening when the new season came. Make sure you report this to Ubisoft Support

**Comment by monolied** [comment]
That's what I thought. That happening on White Noise was expected, but good to have a confirmation. I contacted Ubi support; we'll see.
