### ISSUE TITLE
Sync is way too slow at r6db otherwise its too good

### ISSUE THREAD

**Issue by nitinchand62** [r6db/r6db#66]
Guys please try to sync asap!! Like r6 stat dies in every 15-20minutes it helps alot other wise you guys are best

**Comment by NaughtyMuppet** [comment]
Update button with 2 hour cooldown is on the way. R6stats has less load than we do. Updating on every request would be stupid for us since it would make the site slower for everyone.

**Comment by nitinchand62** [comment]
its better now good work
