### ISSUE TITLE
Global ranking doesn’t show

### ISSUE THREAD

**Issue by dynxsty** [r6db/r6db#67]
The global and Europe rank doesn’t appear it just shows me stats and my past rank from playing the game

**Comment by LaxisB** [comment]
hey, can you link your profile?
usually it's because the account isn't lvl 100 yet or banned.

**Comment by dynxsty** [comment]
https://r6db.com/player/6d7b8ac9-1d94-4bc8-b5c6-df3e78602846

I’m over level 100

**Comment by LaxisB** [comment]
yup, it's the second possibility.
you got removed in the last bomb check with 6.36% bomb.

**Comment by dynxsty** [comment]
So I need to play bomb to get my global ranking?

**Comment by LaxisB** [comment]
yes. otherwise its impossible for us to compare players.
it's explained better here:  https://www.youtube.com/watch?v=hvOCINpJ6LQ
