### ISSUE TITLE
Unify SVG icons style

### ISSUE THREAD

**Issue by GoldMath** [r6db/r6db#69]
Hi,

We actually have .SVG icons made by three different people.

The orignal maker (**DocYen**, from Reddit) of the previous icons (not Y2 S3&S4) updated his pack with the most recent. I recommend to merge them to unify the style. He allow the usage of them.

https://www.reddit.com/r/Rainbow6/comments/7g4lwb/y2s4_operator_icons_download_in_comments/

Download link: https://drive.google.com/file/d/0BxYzSiVtQSX8Vlc0ckZRb2sxVE0/view

**Comment by LaxisB** [comment]
good call. added those
