### ISSUE TITLE
Player social-link query string wrong

### ISSUE THREAD

**Issue by element-code** [r6db/r6db#70]
In the player view `https://r6db.com/player/[ID]` the ESL link ends up in a searching for  `[object Object]` (`https://play.eslgaming.com/search/?query=[object Object]&type=gameaccount`)

![link-bar- r6db](https://user-images.githubusercontent.com/7399618/34395726-17563c0a-eb63-11e7-8146-fc30794d8a73.png)

Seems like a JS object to string transformation.

**Comment by NaughtyMuppet** [comment]
@LaxisB

**Comment by LaxisB** [comment]
fixed on master

**Comment by element-code** [comment]
I don't understand why the code isn'*t open source :(

**Comment by marcopixel** [comment]
@wolf-w The code is open source, just in another repo as it is split up between API and the website.

API: https://github.com/r6db/r6api
Website: https://github.com/r6db/frontend

**Comment by element-code** [comment]
Thank you.

Just why? :D

**Comment by LaxisB** [comment]
it's easier to deploy; that's about it.  
there's no reason for us to keep everything in one repo.

**Comment by marcopixel** [comment]
@wolf-w Probably to make it easier to maintain the project as the API stuff is a standalone package for Node.JS. Most other open source projects do it the same with their webpages, like [Atom](https://github.com/atom) or [Rainmeter](https://github.com/rainmeter).

**Comment by element-code** [comment]
Okay, just want to understand it :)

**Comment by LaxisB** [comment]
no worries :]
