### ISSUE TITLE
My Rank isn't showing

### ISSUE THREAD

**Issue by damsuh** [r6db/r6db#72]
I was just top 20 on the leaderboards and the next day my rank disappeared :(

**Comment by LaxisB** [comment]
that usually means your acc got banned.
we did run the bomb percentage check a day ago; maybe you were one of the ones affected.
send me your profile if you want me to check

**Comment by damsuh** [comment]
my account name is TG Dames, on Xbox leaderboards

**Comment by damsuh** [comment]
​

**Comment by LaxisB** [comment]
i can confirm that account was removed during the secure-area check.
It had 9.24% bomb over 184 ranked games

**Comment by damsuh** [comment]
so am I just not gonna be on the leaderboards anymore ?

**Comment by LaxisB** [comment]
for this season as explained [here](https://medium.com/@r6db/on-excluding-accounts-from-the-leaderboard-596cc217b2af), yes.

**Comment by damsuh** [comment]
I've been playing a lot of bomb lately and have been beating the majority
on the leaderboards, many people are actually questioning why I'm not on
the leaderboards.

**Comment by LaxisB** [comment]
that's possible. doesn't change the fact that it's too late for this season.

**Comment by damsuh** [comment]
I don't think its right to remove someone for the whole season just because
theres a slight different between bomb and secure. If you see someone such
as myself playing more bomb to balance their stats then that should be ok.

**Comment by LaxisB** [comment]
the "slight difference" was 9% bomb vs 91% rest.
[how are we supposed to compare you if you don't play the balanced gamemode?](https://www.youtube.com/watch?v=hvOCINpJ6LQ)

**Comment by damsuh** [comment]
I'm playing bomb every day but will still be removed from the leaderboards?
:/ no sense whats so ever, you guys need to let players play what they'd
like, those game modes are put in the game for a reason, your system is
simply just basing the leaderboards off Bomb only which isn't right at all.

**Comment by damsuh** [comment]
In my opinion I think its ridiculous that Im getting removed from the
leaderboards yet I've been playing bomb everyday :/  and beating multiple
people on the leaderboards

**Comment by LaxisB** [comment]
have you even watched the video i linked in my last comment? was it unclear?

**Comment by damsuh** [comment]
Yes I watched it, but am I clear ? Do you understand what I'm saying? When
I've been trying hard to be on the leaderboards and when I go I get removed
because of unbalanced game modes played.

**Comment by LaxisB** [comment]
yes, i understand what you're saying. that doesn't mean i agree though.
a leaderboard where half the people don't actually play against each other is useless.
you say you're playing bomb every day, but even checking again now, you've *just* cleared the 15% bomb today.
![image](https://i.imgur.com/8zgfs2h.png)  

compare this to geoo (the current pc #1): he has over 99% bomb for ages.

**Comment by damsuh** [comment]
I know who Geo is, I was recently discussing about this with him earlier.
Well thank you for responding to my questions, its been my pleasure.
