### ISSUE TITLE
my rank disappeared

### ISSUE THREAD

**Issue by KliDzer** [r6db/r6db#75]
yesterday i played in ranked and waking up today i saw that everything had disappeared while i was world top 8 i could know why my ID: KliD.Ob8

**Comment by NaughtyMuppet** [comment]
Hi, you were removed for playing with coppers. This ban will be removed at the end of the season since it's your first ban. Next time it's permanent.

**Comment by KliDzer** [comment]
the problem is that I play with a friend dia and another guy classify gold I do not play with copper is not possible

**Comment by NaughtyMuppet** [comment]
Who's the gold you claim to play with?

**Comment by KliDzer** [comment]
dude the gold il my friends

**Comment by NaughtyMuppet** [comment]
What's his uplay nick?

**Comment by KliDzer** [comment]
is RikoTropCalienT

**Comment by NaughtyMuppet** [comment]
So you are saying you have never queued with this guy? https://r6db.com/player/dd1458c2-80f7-44db-a20c-9115892273c9

**Comment by KliDzer** [comment]
yes I think it's a friend to riko the gold

**Comment by LaxisB** [comment]
so now you say he *was* in your party?

**Comment by KliDzer** [comment]
yes he joined but my friends said leave and he did not play with us

**Comment by LaxisB** [comment]
and yet he's in your ranked game.. weird, huh?

https://youtu.be/AslNF5hN4bA?t=45s

**Comment by KliDzer** [comment]
Looooool btw is not me on my acc but np np

**Comment by KliDzer** [comment]
wait what who can you show everything?

**Comment by LaxisB** [comment]
we don't care who plays on your account.

**Comment by KliDzer** [comment]
i know is not you problem
