### ISSUE TITLE
Favourites

### ISSUE THREAD

**Issue by LaxisB** [r6db/r6db#76]
as a user i want to mark certain profiles as favourite so i can find them easily.
Optimally as seperate menu item.

-> just localstorage is fine

**Comment by marcopixel** [comment]
Currently deployed on DEV with https://github.com/r6db/frontend/commit/c2edd1d46561958f6fb0df04fbde8e77d2b30825, needs a little bit of testing and then will be merged to develop.

**Comment by marcopixel** [comment]
~~BUG: On Mobile, the menu will not collapse when clicking on Favorites. Will investigate.~~

Fixed with https://github.com/r6db/frontend/commit/4b04ec1d69423b1b9b10fcdc2eb059c0639fa76c
