### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by Thierryhenry20** [r6db/r6db#77]
Why am I not on the leaderboard

**Comment by LaxisB** [comment]
typically that's because an account got removed. if you link your profile i can look it up.
(or email us if you don't want to do this publicly)

**Comment by Thierryhenry20** [comment]
How do I link my profile?

**Comment by LaxisB** [comment]
just go to your r6db profile and paste the url here

**Comment by Thierryhenry20** [comment]
Like this?
https://github.com/Thierryhenry20#

**Comment by LaxisB** [comment]
i honestly don't know how to respond to that..
