### ISSUE TITLE
Profilepic loading buggy

### ISSUE THREAD

**Issue by LaxisB** [r6db/r6db#79]
the profilepics don't seem to always load on mobile

**Comment by marcopixel** [comment]
Can't reproduce it on Chrome 63.0.3239.111 on Android 8.0.0, it's loading fine here.

**Comment by LaxisB** [comment]
seems to have been just unfortunate timing ![2018-01-07 11_15_33-nvidia geforce overlay](https://user-images.githubusercontent.com/8034086/34648590-1852c1fa-f39c-11e7-9c50-1991ed59e490.png)
