### ISSUE TITLE
Says I Play American Servers?

### ISSUE THREAD

**Issue by Mxrauder** [r6db/r6db#81]
My Global ranking is being destroyed by these false stats, i play on NEU and WEU seevrs i am from Scotland and have never played American servers. Can these stats be taken off?

**Comment by LaxisB** [comment]
we get the stats directly from ubi. it is higly unlikely that they create fictional matches.
Maybe you joined a mate who was on us servers.  
it doesn't affect your global rank either way, since that uses your highest/best region
