### ISSUE TITLE
Refining the color scale gradiant

### ISSUE THREAD

**Issue by GoldMath** [r6db/r6db#82]
Hi,

The scale actually use 6 tier colours but I found them not exactly equilibrate. 
It should be refine with top-tier player stats and the global average.

I'm not sure how exactly your code is done but scale should be independent of the various ratio.
One specific for Win Ratio, K/D, K/r and Survival rate based on the results.

Here my quick recommendations, but would be better if based on big data.

- Over 75% **win rate** should be rather consider _nutty-tier_
  - less 35% low
  - 35% to 45% med-low
  - 45% to 55% med 
  - 55% to 65% med-high
  - 65% to 75% high
  - more 75% nutty

- **K/D** is a bit tricky to equilibrate but here my shoot:
  - less 0.50 low
  - 0.50 to 1.00 med-low
  - 1.00 to 1.50 med 
  - 1.50 to 2.00 med-high
  - 2.00 to 2.50 high
  - more 2.50 nutty

- on many top-tier pro league players 1.50 **kills by rounds** looks like an exceptional high.
  - less 0.30 low
  - 0.30 to 0.60 med-low
  - 0.60 to 0.90 med 
  - 0.90 to 1.20 med-high
  - 1.20 to 1.50 high
  - more 1.50 nutty

- comparing various **survival rate** of top-tier players it's look like:
  - less 35% low
  - 35% to 40% med-low
  - 40% to 45% med 
  - 45% to 50% med-high
  - 50% to 55% high
  - more 55% nutty

- I also suggest this color palette:

#FF0303 (red) #FF6101 (orange) #FFBF00 (yellow) #25CD2B (green) #30AEF2 (blue) #00FFF2 (cyan)

![gradient](https://user-images.githubusercontent.com/7282547/34781916-65cbd11e-f627-11e7-9a15-23a3ea994cf7.jpg)

My idea with the new colours was this:
- The **Blue&Cyan** distinctly show Top-Tier, high stats and exceptional performances.
- The classic **Red-Orange-Yellow-Green** is great to show stats for the more average players (they will probably never have Blueish stats or really few regarding my scaling suggestion)

Regards,

**Comment by LaxisB** [comment]
agreed on updating the scaling, but not with the colors necessarily. 
it feels like rainbow-mode to me. as comparison: these are the colors i set in the current dev build:
![2018-01-10 18_47_37-r6db - rainbow 6 player database - firefox developer edition](https://user-images.githubusercontent.com/8034086/34787206-c5b529b8-f636-11e7-8da5-71a92f32b682.png)  
coincidentally i also called the new tier "nutty".  
the scale itself is currently just a pseudo-fixed percentage-based system (<50% of given "neutral" value is bad, >250% is nutty). it would make most sense to define specific scales for the values they represent and reuse those. (e.g it's impossible to get 'nutty' winrate atm, since 250% of 50% win rate is impossible)

**Comment by GoldMath** [comment]
The nutty name was based on your css; sorry no magic here!

My idea with the new colours was this:
- The **Blue&Cyan** distinctly show Top-Tier, high stats and exceptional performances.
- The classic **Red-Orange-Yellow-Green** is great to show stats for the more average players (they will probably never have Blueish stats or really few regarding my scaling suggestion)

My issue with the actual colours is the _double green_, the more bright one looks better than the darker.
If you wanna keep it that way; maybe reverse the greens and make the Cyan more bright to compensate.

**Comment by LaxisB** [comment]
its probably best to just hue rotate, so we keep the same intensity

**Comment by GoldMath** [comment]
Hi, I see you made nice changes to the scale with the recent update; the colors feel better too

I still think some scale need rework : 
- **kill/round** : 0.70 is considered low (red) which seem too harsh
- **survival** : starting 35% is considered med-high
  - less 30% is considered medium (yellow), imo should be considered at least med-low
  - for exemple I saw 17,85% and 8.57% still being marked as medium (yellow) which should be low

The color gradient could be also used in the Summary page of players.

Also you should think about a color gradient for the **Skill Rating**. It's not very talkative in it's form.

**Comment by LaxisB** [comment]
good call. i'll adjust them a bit:

```javascript
const kprScale = {
    "med-low": 0.5,
    med: 0.7,
    "med-high": 0.9,
    high: 1.1,
    nutty: 1.3,
};
const survivalScale = {
    "med-low": 3,
    med: 0.4,
    "med-high": 0.5,
    high: 0.55,
    nutty: 0.6,
};

i'll add them to the summary at some point, but that'll take a bit.
as for skill-rating: it's directly tied to mmr and rank, so i didn't want to add an unnecessary scale here
