### ISSUE TITLE
Comparisons Feedback / Bugs

### ISSUE THREAD

**Issue by LaxisB** [r6db/r6db#88]

**Comment by GoldMath** [comment]
Hello,

Tested on Opera 50.0

- No mouse feedback (hand) when you search, then click on a player. 
Maybe add a mouse-over background too.

- After selecting a player there is no feedback, so it's really confuse what to do next. Maybe add a "Validate" box on top after selecting a player (acting like the close window cross).

- With the new website, there is no link to the GitHub.

- Alignment problem when comparing two players, same happen with multiple.
Colours gradient not used in that table.

- It's would be nice to have alt-background color each row, or on mouse-over to read faster.
(_this could also be added to the player page too_)

![comapre](https://user-images.githubusercontent.com/7282547/34917787-09706db8-f94b-11e7-9a34-6500987a2ee9.JPG)

**Comment by ghost** [comment]
The search button for comparing players on console isn’t working

**Comment by LaxisB** [comment]
@slenderm0nkey on what system does that happen?
i can't replicate that at all

**Comment by ghost** [comment]
@LaxisB I’ve tried on PC, iPhone and iPad, I believe this is what’s happening.

when comparing players on console, when you type a name in, it searches for a pc name instead of searching for a console name

**Comment by LaxisB** [comment]
@slenderm0nkey yeah, that was the bug. my clickhandler threw an error there.
this is fixed on https://dev.r6db.com already, but i forgot to deploy ot prod yesterday.
