### ISSUE TITLE
i find a boosted on leaderbord

### ISSUE THREAD

**Issue by chuk-R6** [r6db/r6db#89]
I find a guy who has boost to be in the leaderbord he's called Wezup I have evidence attached 
![screen wezup](https://user-images.githubusercontent.com/35709385/35248440-644b4c42-ffce-11e7-8797-ce38161f7304.jpg)
R6DB : https://r6db.com/player/12420ec3-bc8b-45bd-ab23-44a5d0974559

**Comment by NaughtyMuppet** [comment]
This is from last season, he already was banned last season for it after he sent a screenshot in himself
