### ISSUE TITLE
Player ''AKIRA7.'' playing with coppers to get diamond, heres proof.

### ISSUE THREAD

**Issue by rainbowsixplayer** [r6db/r6db#93]
The player AKIRA7. is playing with coppers. hes #1972 global / lvl 177 and i want him to get removed from the leaderboard.
Proof:
![20180211213819_1](https://user-images.githubusercontent.com/36388610/36080532-ad17ea5c-0f78-11e8-8d83-c62a83180f68.jpg)

Profile: https://r6db.com/player/dfab6406-7296-4ecd-b24d-0b6b84ad78de

**Comment by NaughtyMuppet** [comment]
Handled
