### ISSUE TITLE
Preperation for Y3S1

### ISSUE THREAD

**Issue by marcopixel** [r6db/r6db#99]
- [x] add season to constants
- [x] add color for rankoverview
- [x] add classes for rankoverview
- [x] add operators
- [x] add operators to backend fetching
- [x] add svg icons of operators (https://drive.google.com/drive/folders/1jDco6F3gliOf9M0TdkiWE5it_-wpC3sx)
- [x] add seasoncard season svgs (already exists)
- [x] add seasoncard background image (on redesign-2018)

**Comment by LaxisB** [comment]
did some tasks from this. you might need to fix the cover import in constants.ts

**Comment by marcopixel** [comment]
Fixed it in https://github.com/r6db/frontend/commit/2280992abdc77451239c0382e11df460ec2f91b6, also added the svgs and backgrounds to the develop branch.

**Comment by LaxisB** [comment]
neat, i'll assign this to muppet for the backend then
